name: Chinese
description: Submit issue with chinese
body:
- type: markdown
  attributes:
    value: |
      > 来自开发者的话：
      > 您好！感谢使用我的插件。不像很多其他思源插件，我的插件是100%免费且100%开源的，这会让您更放心的使用我的插件。
      > 同时，由于该插件的100%开源免费，我从维护和编写这个插件中，唯一能得到的只有您的鼓励。
      > 所以，在您继续提交issue之前，希望您能给这个仓库点击一个免费的⭐星星（star）。（[怎么点？](https://docs.github.com/zh/get-started/exploring-projects-on-github/saving-repositories-with-stars#starring-a-repository)）
- type: textarea
  id: description
  attributes:
    label: 功能请求
    description: "如果是（添加）功能请求，请在下面填写"
  validations:
    required: false
- type: textarea
  id: repro
  attributes: 
    label: 汇报Bug
    description: "请仔细描述bug的复现步骤，最好同时上传你发现问题的文档和思源的日志"
    placeholder: |
      1. Switch on...
      2. Press button '....'
      3. Wait for the end of the universe
      4. It burns
  validations:
    required: false
